blank_issues_enabled: false
contact_links: 
    - name: Bend2 Related Issues
      url: https://github.com/HigherOrderCO/Bend2/issues/new/choose
      about: For Bend2 related Issues, please Report them on the Bend2 repository.
